# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c7ed7a6148dfa9255db98fcfd5d1aed1fa4125c3ab8ecbdfdc8473f2bedd8655cb8043a5d2047e0bf3ab685140e2f7ec6e0a222553acb3fe573e6505c079467

test:
  secret_key_base: d1d5e59640c74d3048e04d7191d0b5c54fc2ce5bca09ba85c7ccbc3d1073a93ae53eb13dbc37f58ad179b7bdabd3a08d62ff11cb1db5c1948c4903335a7db765

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>